#!/bin/bash

ADDRESS="$1"
WAIT_TIME="$2"
SSH_CONN="$ADDRESS"
# If no address i specified
# print help and exit
if [ -z "$ADDRESS" ]; then
    echo
    echo "No address specified"
    echo "Usage:"
    echo "pinssh <address> <wait_time i seconds default=1> <max_retries default=100>"
    echo
    exit 1
fi

# Set the default wait time
# between pings to 1
if [ -z "$WAIT_TIME" ]; then
    WAIT_TIME="1"
else
    echo "Waiting $WAIT_TIME seconds between pings"
fi

# Check if a user is specified if so split
# the string so we can ping the address
if [ ! -z $(echo $ADDRESS |grep "@" ) ]; then
    SSH_USER=$(echo $ADDRESS |cut -f 1 -d"@")
    ADDRESS=$(echo $ADDRESS |cut -f 2 -d"@")
    SSH_CONN="$SSH_USER@$ADDRESS"    
fi

# Forever ping the host until 
while true
do
    ping -t 1 -c 1 "$ADDRESS" > /dev/null
    PING_STATUS="$?"
    if [ "$PING_STATUS" -eq "0" ]; then
        echo "SSHing to $SSH_CONN"
        break
    else
        echo "$ADDRESS not up"
    fi
    sleep $WAIT_TIME
done

ssh "$SSH_CONN"