#!/bin/bash

ADDRESS="$1"
WAIT_TIME="$2"
SSH_CONN="$ADDRESS"
MAX_RETRIES="$3"

# If no address i specified
# print help and exit
if [ -z "$ADDRESS" ]; then
    echo
    echo "No address specified"
    echo "Usage:"
    echo "pinssh <address> <wait_time i seconds default=1> <max_retries default=100>"
    echo
    exit 1
fi

# Set the default wait time
# between pings to 1
if [ -z "$WAIT_TIME" ]; then
    WAIT_TIME="1"
else
    echo "Waiting $WAIT_TIME seconds between pings"
fi

# Set the default max retries
# between ssh attempts to 10
if [ -z "$MAX_RETRIES" ]; then
    MAX_RETRIES="100"
else
    echo "Max $MAX_RETRIES SSH attempts"
fi

echo

# Check if a user is specified if so split
# the string so we can ping the address
if [ ! -z $(echo $ADDRESS |grep "@" ) ]; then
    SSH_USER=$(echo $ADDRESS |cut -f 1 -d"@")
    ADDRESS=$(echo $ADDRESS |cut -f 2 -d"@")
    SSH_CONN="$SSH_USER@$ADDRESS"    
fi

# Forever ping the host until it is up
while true
do
    ping -t 1 -c 1 "$ADDRESS" > /dev/null
    PING_STATUS="$?"
    if [ "$PING_STATUS" -eq "0" ]; then
        echo "SSHing to $SSH_CONN"
        echo
        sleep 1
        break
    else
        echo "$ADDRESS not up"
    fi
    sleep $WAIT_TIME
done


# Try to ssh to the host
for i in $(seq 1 $MAX_RETRIES);
do
    ssh "$SSH_CONN"
    SSH_STATUS="$?"
    if [ "$SSH_STATUS" -ne "255" ]; then
        exit 0
    else
        echo "Problem SSHing to $SSH_CONN, retrying..."
        echo
    fi

    sleep $WAIT_TIME
done

echo "Max retries reached, exiting..."
exit 1

